/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val f1 = Fraccion(2, 3)
    val f2 = Fraccion(3, 4)

    println("Fracción 1: $f1")
    println("Fracción 2: $f2")

    // Suma
    println("Suma: ${f1 + f2}")

    // Resta
    println("Resta: ${f1 - f2}")

    // Multiplicación
    println("Multiplicación: ${f1 * f2}")

    // División
    println("División: ${f1 / f2}")

    // Prueba de división por fracción con numerador cero
    try {
        val f3 = Fraccion(0, 5)
        println("División inválida: ${f1 / f3}")
    } catch (e: IllegalArgumentException) {
        println("Error al dividir: ${e.message}")
    }
}
