/*

 * This source file was generated by the Gradle 'init' task

 */

package org.example

import java.util.Scanner

fun mostrarMenu() {
    println("=== CALCULADORA DE FRACCIONES ===")
    println("1. Sumar fracciones")
    println("2. Restar fracciones")
    println("3. Multiplicar fracciones")
    println("4. Dividir fracciones")
    println("5. Comparar fracciones")
    println("6. Convertir fracción a decimal")
    println("7. Crear fracción desde decimal")
    println("8. Ejemplos predefinidos")
    println("0. Salir")
    print("Ingrese su opción: ")
}

// Función para leer una fracción
fun leerFraccion(scanner: Scanner, mensaje: String): Fraccion {
    println(mensaje)
    print("Numerador: ")
    val numerador = scanner.nextInt()
    print("Denominador: ")
    val denominador = scanner.nextInt()
    return Fraccion(numerador, denominador)
}

// Operaciones
fun realizarSuma(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la primera fracción para sumar:")
    val f2 = leerFraccion(scanner, "Ingrese la segunda fracción para sumar:")
    println("Resultado de la suma: ${f1 + f2}")
}

fun realizarResta(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la primera fracción para restar:")
    val f2 = leerFraccion(scanner, "Ingrese la segunda fracción para restar:")
    println("Resultado de la resta: ${f1 - f2}")
}

fun realizarMultiplicacion(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la primera fracción para multiplicar:")
    val f2 = leerFraccion(scanner, "Ingrese la segunda fracción para multiplicar:")
    println("Resultado de la multiplicación: ${f1 * f2}")
}

fun realizarDivision(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la primera fracción para dividir:")
    val f2 = leerFraccion(scanner, "Ingrese la segunda fracción para dividir:")
    try {
        println("Resultado de la división: ${f1 / f2}")
    } catch (e: IllegalArgumentException) {
        println("Error al dividir: ${e.message}")
    }
}

fun realizarComparacion(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la primera fracción para comparar:")
    val f2 = leerFraccion(scanner, "Ingrese la segunda fracción para comparar:")
    println("¿$f1 es mayor que $f2? ${f1.esMayor(f2)}")
    println("¿$f1 es menor que $f2? ${f1.esMenor(f2)}")
}

fun convertirADecimal(scanner: Scanner) {
    val f1 = leerFraccion(scanner, "Ingrese la fracción para convertir a decimal:")
    println("Valor decimal de la fracción: ${f1.aDecimal()}")
}

fun crearDesdeDecimal(scanner: Scanner) {
    print("Ingrese un número decimal: ")
    val decimal = scanner.nextDouble()
    val fraccion = Fraccion.desdeDecimal(decimal)
    println("Fracción equivalente a $decimal: $fraccion")
}

fun mostrarEjemplos() {
    println("\n=== EJEMPLOS PREDEFINIDOS ===")
    
    val f1 = Fraccion(1, 2)  // 1/2
    val f2 = Fraccion(1, 3)  // 1/3
    
    println("Fracción 1: $f1")
    println("Fracción 2: $f2")
    println("Suma: $f1 + $f2 = ${f1 + f2}")
    println("Resta: $f1 - $f2 = ${f1 - f2}")
    println("Multiplicación: $f1 * $f2 = ${f1 * f2}")
    println("División: $f1 / $f2 = ${f1 / f2}")
    println("¿$f1 > $f2? ${f1 > f2}")
    println("$f1 en decimal: ${f1.aDecimal()}")
}

// Función para leer la opción
fun leerOpcion(scanner: Scanner): Int {
    var opcion: Int
    while (true) {
        try {
            print("Ingrese su opción: ")
            opcion = scanner.nextInt()
            scanner.nextLine()  // Limpiar el buffer de entrada
            return opcion
        } catch (e: java.util.InputMismatchException) {
            println("Entrada inválida. Por favor ingrese un número.")
            scanner.nextLine()  // Limpiar el buffer de entrada
        }
    }
}

fun main() {
    val scanner = Scanner(System.`in`)
    var opcion: Int

    do {
        mostrarMenu()  // Mostrar el menú
        opcion = leerOpcion(scanner)  // Leer opción de usuario

        when (opcion) {
            1 -> realizarSuma(scanner)
            2 -> realizarResta(scanner)
            3 -> realizarMultiplicacion(scanner)
            4 -> realizarDivision(scanner)
            5 -> realizarComparacion(scanner)
            6 -> convertirADecimal(scanner)
            7 -> crearDesdeDecimal(scanner)
            8 -> mostrarEjemplos()  // Mostrar ejemplos
            0 -> println("¡Hasta luego!")
            else -> println("Opción no válida. Intente de nuevo.")
        }

        if (opcion != 0) {
            println("\nPresione Enter para continuar...")
            scanner.nextLine()  // Limpiar el buffer de entrada
            scanner.nextLine()  // Esperar el Enter
        }
    } while (opcion != 0)
    
    scanner.close()  // Cerrar el scanner
}
